language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  
before_install:
 - curl -sS https://getcomposer.org/installer | php

before_script:
 - php composer.phar install --dev

script:
 - (cd tests ; phpunit)
